services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserverexpress
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
    restart: always
    volumes:
      - mssql_data:/var/opt/mssql
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
      interval: 8s
      timeout: 4s
      retries: 4
      start_period: 20s
    
  webapi:
    build:
      context: .
      dockerfile: MetaExchanger.Api/Dockerfile
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      - Database__ConnectionString=Server=mssql,1433;Database=MyDatabase;User Id=sa;Password=YourStrong!Passw0rd;TrustServerCertificate=True;
    ports:
      - "8080:8080"

volumes:
  mssql_data: